function results_table = import_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSTABLE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESULTSTABLE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  resultstable = importfile("/Users/ernest/PycharmProjects/EARIN_Bridges/results_table.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Apr-2019 12:54:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Size", "Depth", "IDFStime", "Atime", "IDFSnodes", "Anodes"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
results_table = readtable(filename, opts);
results_table(1, :) =[];

end